# Generated by Django 5.0.4 on 2024-04-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('phone', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('specilization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('phone', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('expertise', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomeOwner',
            fields=[
                ('phone', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('phone', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('phone', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('categloge', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmh_app.homeowner')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmh_app.homeowner')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmh_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('projectID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('timeline', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=50)),
                ('architech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmh_app.architect')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmh_app.contractor')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmh_app.homeowner')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmh_app.supplier')),
            ],
        ),
    ]
