# Generated by Django 5.0.4 on 2024-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='specilization',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='expertise',
            field=models.CharField(max_length=250),
        ),
    ]
