# Generated by Django 5.0.4 on 2024-04-30 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmh_app', '0004_rename_comment_feedback_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='pics')),
                ('quantity', models.CharField(max_length=50)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mmh_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='pics')),
                ('category', models.CharField(max_length=50)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mmh_app.architect')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='contracts')),
                ('ratings', models.CharField(default='*****', max_length=50)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mmh_app.contractor')),
            ],
        ),
    ]
